language: ruby

bundler_args: --without development

cache: bundler

before_install:
  - gem --version

script: bundle exec rake test

rvm:
  - 2.3.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email:
    recipients:
      - ngiger@ywesee.com
      - yasaka@ywesee.com
