language: ruby

bundler_args: --without development

cache:
  bundler:
  directories:
    - dojo
    - downloads

sudo: required
dist: trusty # or installing google-chrome-stable will fail

before_install:
  - mv etc/config.yml.ci etc/config.yml
  - test/travis_setup

script: bundle exec rake test

rvm:
  - 2.3.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - ngiger@ywesee.com
      - yasaka@ywesee.com
